# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Frontend

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: yarn install
    - run: yarn run build --if-present
    - run: yarn test
      env:
        CI: true
    
    - name: Package build
      run: tar -czf build.tar.gz build
      
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2.0.1
      with:
        key: ${{ secrets.WALLE_SSH_KEY_FOR_DEPLOYMENT }}
        known_hosts: ${{ secrets.WALLE_KNOWNHOST }}
        
    - name: Upload build
      run: scp build.tar.gz root@${{ secrets.WALLE_VPS_IP }}:/tmp
    - name: Extract files
      run: ssh root@${{ secrets.WALLE_VPS_IP }} "tar -xzf /tmp/build.tar.gz -C /tmp && mv /tmp/build /var/www/solipool-frontend"
      
